# Generated by Django 4.2.6 on 2023-11-09 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('idaula', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('idprograma', models.IntegerField(primary_key=True, serialize=False)),
                ('info_programa', models.TextField()),
                ('facultad', models.CharField(max_length=45)),
                ('jefe_programa', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('num_clases_rest', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=200)),
                ('ciclo', models.CharField(max_length=45)),
                ('grupo', models.CharField(max_length=45)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curso.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_fin', models.DateTimeField()),
                ('hora_inicio', models.DateTimeField()),
                ('tema', models.CharField(max_length=45)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curso.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curso.curso')),
            ],
        ),
    ]
